name: Setup Project
description: Setup the project for the workflow

inputs:
  bun_version:
    description: The Bun version to test
    required: false

runs:
  using: composite
  steps:
    - name: Get Bun version
      if: inputs.bun_version == null
      id: get-bun-version
      shell: bash
      run: |
        BUN_VERSION=$(cat packages/bun-workspaces/package.json | jq -r '._bwInternal.bunVersion.build')
        echo BUN_VERSION=$BUN_VERSION >> $GITHUB_ENV
        echo "Bun version to be installed: $BUN_VERSION"

    - name: Install Bun
      shell: bash
      id: install-bun
      run: |
        bun_version=${{ inputs.bun_version || env.BUN_VERSION }}
        echo "Installing Bun version: $bun_version"
        export BUN_INSTALL="$HOME/.bun"
        curl -fsSL https://bun.com/install | bash -s "bun-v$bun_version"
        echo "$HOME/.bun/bin:$PATH" >> $GITHUB_PATH

    - name: Install Dependencies
      id: install-deps
      shell: bash
      run: |
        bun install --frozen-lockfile
