name: Setup Project
description: Setup the project for the workflow

runs:
  using: composite
  steps:
    - name: Get Bun version
      id: get-bun-version
      shell: bash
      run: |
        BUN_VERSION=$(cat packages/bun-workspaces/package.json | jq -r '._bwInternal.bunVersion.build')
        echo BUN_VERSION=$BUN_VERSION >> $GITHUB_ENV
        echo "Bun version to be installed: $BUN_VERSION"

    - name: Install Bun
      id: install-bun
      shell: bash
      run: |
        echo "Installing Bun version: $BUN_VERSION"
        BUN_INSTALL="$HOME/.bun"
        curl -fsSL https://bun.com/install | bash -s "bun-v$BUN_VERSION"
        echo "$HOME/.bun/bin:$PATH" >> $GITHUB_PATH
        echo "Bun version: $(bun --version)"

    - name: Install Dependencies
      id: install-deps
      shell: bash
      run: |
        bun install --frozen-lockfile