name: Install Bun Dependencies
description: Install the dependencies for the project

runs:
  using: composite
  steps:
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }} Bun Cache
      id: bun-cache

    - name: Install Dependencies
      id: install-deps
      run: bun install --frozen-lockfile
      shell: bash
